# Gradient Descent Implementation

Implement GD with different learning rates to minimise functions of the form $f(x)=\sum_{i=1}^{n}a_ix_i²$

In [29]:
import numpy as np

In [269]:
class f:
    def __init__(self, list_of_parameters, initial_inputs):
        self.params = np.array(list_of_parameters)
        self.inputs = np.array(initial_inputs)
    
    def update_inputs(self, list_of_inputs):
        self.inputs = np.array(list_of_inputs)
        return self
        
    def evaluate(self):
        return self.params.dot(self.inputs ** 2)
    
    def gradient(self):
        return 2 * self.inputs * self.params
        
    def hessian(self):
        dim = len(self.params)
        hess = np.zeros((dim,dim))
        np.fill_diagonal(hess, 2 * self.params)
        return hess

In [108]:
func = f([5,3],[5,6])

In [109]:
func.params

array([5, 3])

In [110]:
func.inputs

array([5, 6])

In [111]:
func.evaluate()

233

In [112]:
func.update_inputs([1,0.5])

In [113]:
func.inputs

array([1. , 0.5])

In [114]:
func.evaluate()

5.75

In [115]:
func.gradient()

array([10.,  3.])

In [116]:
func.hessian()

array([[10.,  0.],
       [ 0.,  6.]])

Let's try to minimise $f(x)=\sum_{i=1}^{10}x_i^2$, which obviously should have as solution the zero vector. At first, we'll use the fixed learning rate approach.

In [182]:
def gradient_descent_PF_with_print(f_params, initial_inputs, t):
    k=0
    x = initial_inputs
    func = f(f_params, x)
    
    while (np.linalg.norm(func.gradient()) > 0.000000001 and k < 10001):
        dk = func.gradient()
        x_next = x - t*dk
        func.update_inputs(x_next)
        x = x_next.copy()
        k = k + 1
        
        if k % 25 == 0:
            print('Iteration number {}'.format(k) + ":")
            print('The current value of f is {}'.format(func.evaluate()))
            print('The current value of the norm of the gradient of f is {}'.format(np.linalg.norm(func.gradient())))
            print('')
    
    print('-----------------------------------------------------------------------')
    print('The process ended in the iteration of number {} '.format(k))
    print('The current value of f is {}'.format(func.evaluate()))
    print('The current value of the norm of the gradient of f is {}'.format(np.linalg.norm(func.gradient())))
    return(x,k)

In [183]:
def gradient_descent_PF(f_params, initial_inputs, t):
    k=0
    x = initial_inputs
    func = f(f_params, x)
    
    while (np.linalg.norm(func.gradient()) > 0.000000001 and k < 10001):
        dk = func.gradient()
        x_next = x - t*dk
        func.update_inputs(x_next)
        x = x_next.copy()
        k = k + 1

    return(x,k)

In [184]:
gradient_descent_PF_with_print([1,1,1,1,1,1,1,1,1,1],[6,7,3,9,3,4,1,1,0,4],0.05)

Iteration number 25:
The current value of f is 1.123522995195784
The current value of the norm of the gradient of f is 2.119927352713563

Iteration number 50:
The current value of f is 0.005790384957494062
The current value of the norm of the gradient of f is 0.15218915805659827

Iteration number 75:
The current value of f is 2.9842342434772212e-05
The current value of the norm of the gradient of f is 0.010925629031734916

Iteration number 100:
The current value of f is 1.5380072456868595e-07
The current value of the norm of the gradient of f is 0.0007843487096150179

Iteration number 125:
The current value of f is 7.926543611499628e-10
The current value of the norm of the gradient of f is 5.630823602813225e-05

Iteration number 150:
The current value of f is 4.08516239446884e-12
The current value of the norm of the gradient of f is 4.0423569335074015e-06

Iteration number 175:
The current value of f is 2.105400866648997e-14
The current value of the norm of the gradient of f is 2.90199

(array([1.99381983e-10, 2.32612314e-10, 9.96909917e-11, 2.99072975e-10,
        9.96909917e-11, 1.32921322e-10, 3.32303306e-11, 3.32303306e-11,
        0.00000000e+00, 1.32921322e-10]), 229)

In [185]:
g01 = gradient_descent_PF([1,1,1,1,1,1,1,1,1,1],[6,7,3,9,3,4,1,1,0,4],0.1)

In [186]:
g02 = gradient_descent_PF([1,1,1,1,1,1,1,1,1,1],[6,7,3,9,3,4,1,1,0,4],0.2)

In [187]:
g03 = gradient_descent_PF([1,1,1,1,1,1,1,1,1,1],[6,7,3,9,3,4,1,1,0,4],0.3)

In [188]:
g04 = gradient_descent_PF([1,1,1,1,1,1,1,1,1,1],[6,7,3,9,3,4,1,1,0,4],0.4)

In [189]:
g05 = gradient_descent_PF([1,1,1,1,1,1,1,1,1,1],[6,7,3,9,3,4,1,1,0,4],0.5)

In [190]:
g075 = gradient_descent_PF([1,1,1,1,1,1,1,1,1,1],[6,7,3,9,3,4,1,1,0,4],0.75)

In [191]:
g09 = gradient_descent_PF([1,1,1,1,1,1,1,1,1,1],[6,7,3,9,3,4,1,1,0,4],0.9)

In [192]:
g1 = gradient_descent_PF([1,1,1,1,1,1,1,1,1,1],[6,7,3,9,3,4,1,1,0,4],1)

In [194]:
g01[1], g02[1], g03[1], g04[1], g05[1], g075[1], g09[1], g1[1]

(109, 48, 27, 15, 1, 35, 109, 10001)

Let's calculate the learning rate in an optimal rate for this fixed method. That is, $t=\frac{2}{\mu+L}$, such that $\mu$ is the smaller eigenvalue of the Hessian Matrix of $f$, and $L$ is the greater eigenvalue.

In [212]:
def gradient_descent_PF_optimal(f_params, initial_inputs):
    k=0
    x = initial_inputs
    func = f(f_params, x)
    
    eigenvals = np.linalg.eig(func.hessian())[0]
    eigenmax = eigenvals.max()
    eigenmin = eigenvals.min()
    t = 2/(eigenmax+eigenmin)
    print('The optimal learning rate is: {}'.format(t))
    
    while (np.linalg.norm(func.gradient()) > 0.000000001 and k < 10001):
        dk = func.gradient()
        x_next = x - t*dk
        func.update_inputs(x_next)
        x = x_next.copy()
        k = k + 1
    
    print('The process converged in the interation: {}'.format(k))
    return(x,k)

In [213]:
gradient_descent_PF_optimal([1,1,1,1,1,1,1,1,1,1],[6,7,3,9,3,4,1,1,0,4])[1]

The optimal learning rate is: 0.5
The process converged in the interation: 1


1

In [256]:
def gradient_descent_PF(f_params, initial_inputs, t_option):
    '''
    choose t_option:
    A: 2/(L+mu)
    B: 1/L
    else: personal input
    '''
    k=0
    x = initial_inputs
    func = f(f_params, x)
    
    eigenvals = np.linalg.eig(func.hessian())[0]
    eigenmax = eigenvals.max()
    eigenmin = eigenvals.min()
    
    if t_option == 'A':
        t = 2/(eigenmax+eigenmin)
    elif t_option == 'B':
        t = 1/eigenmax
    else:
        t = t_option
        
    print('The learning rate is: {}'.format(t))
    
    while (np.linalg.norm(func.gradient()) > 0.000000001 and k < 10001):
        dk = func.gradient()
        x_next = x - t*dk
        func.update_inputs(x_next)
        x = x_next.copy()
        k = k + 1
    
    print('The process converged in the interation: {}'.format(k))
    print('The final value of f was: {}'.format(func.evaluate()))
    return(x,k)

In [243]:
#NEW FUNCTION

In [257]:
gradient_descent_PF([10,10,10,10,10,1,1,1,1,1],[6,7,3,9,3,4,1,1,0,4],'A')[1]

The learning rate is: 0.09090909090909091
The process converged in the interation: 132
The final value of f was: 1.841294249224644e-20


132

In [258]:
gradient_descent_PF([10,10,10,10,10,1,1,1,1,1],[6,7,3,9,3,4,1,1,0,4],'B')[1]

The learning rate is: 0.05
The process converged in the interation: 221
The final value of f was: 2.026133649330505e-19


221

In [259]:
gradient_descent_PF([100,100,100,100,100,1,1,1,1,1],[6,7,3,9,3,4,1,1,0,4],'A')[1]

The learning rate is: 0.009900990099009901
The process converged in the interation: 1432
The final value of f was: 2.4456955708594068e-21


1432

In [260]:
gradient_descent_PF([10,10,10,10,10,1,1,1,1,1],[6,7,3,9,3,4,1,1,0,4],'B')[1]

The learning rate is: 0.05
The process converged in the interation: 221
The final value of f was: 2.026133649330505e-19


221

In [261]:
gradient_descent_PF([100,100,100,100,100,50,50,50,10,1],[6,7,3,9,3,4,1,1,0,4],'A')[1]

The learning rate is: 0.009900990099009901
The process converged in the interation: 1432
The final value of f was: 2.4433074554056004e-21


1432

In [262]:
gradient_descent_PF([100,100,100,100,100,50,50,50,10,1],[6,7,3,9,3,4,1,1,0,4],'B')[1]

The learning rate is: 0.005
The process converged in the interation: 2269
The final value of f was: 2.492487944014172e-19


2269

Now let's implement the gradient descent with linear backtracking updates for the learning rate.

Do $t_k = t_k/2$ while:

$f(x_k-t_kd_k) >= f(x_k)-\alpha t_kd_k'd_k$

being $d_k$ the gradient of $f$ at iteration $k$, and $t_k$ the learning rate at iteration $k$.

In [299]:
def update(func,x,t,dk):
    return func.update_inputs(x-t*dk).evaluate()

def expression(func,x,alpha,t,dk):
    return func.update_inputs(x).evaluate() - alpha*t*func.gradient().T.dot(dk)

In [311]:
def gradient_descent_backtracking(f_params, initial_inputs, alpha, t0):
    k=0
    x = initial_inputs
    func = f(f_params, x)
    list_t = []
    
    while (np.linalg.norm(func.gradient()) > 0.000000001 and k < 10001):
        dk = func.gradient()
        t = t0
        
        while (func.update_inputs(x - t*dk).evaluate() >= 
               func.update_inputs(x).evaluate() - alpha * t * func.gradient().T.dot(dk)):
            t=t/2
        
        list_t.append(t)
        
        x_next = x - t*dk
        func.update_inputs(x_next)
        x = x_next.copy()
        k = k + 1
    
    print('The process converged in the interation: {}'.format(k))
    print('The final value of f was: {}'.format(func.evaluate()))

    return(x,k,list_t)

In [317]:
gradient_descent_backtracking([1,2], [1,2], 0.1, 1)
#CONVERGED IN 2 ITERATIONS!!!!!!!!!!!!!!

The process converged in the interation: 2
The final value of f was: 0.0


(array([0., 0.]), 2, [0.25, 0.5])

In [318]:
gradient_descent_PF([1,2],[1,2],'A')

The learning rate is: 0.3333333333333333
The process converged in the interation: 21
The final value of f was: 8.225263339969886e-20


(array([ 9.55990664e-11, -1.91198133e-10]), 21)

In [319]:
gradient_descent_PF([1,2],[1,2],'B')

The learning rate is: 0.25
The process converged in the interation: 31
The final value of f was: 2.168404344971009e-19


(array([4.65661287e-10, 0.00000000e+00]), 31)

In [348]:
gradient_descent_backtracking([10,10,10,10,10,1,1,1,1,1],[6,7,3,9,3,4,1,1,0,4],0.1,1)[0]

The process converged in the interation: 83
The final value of f was: 1.437910511244278e-19


array([-1.26154928e-11, -1.47180749e-11, -6.30774640e-12, -1.89232392e-11,
       -6.30774640e-12,  2.52662699e-10,  6.31656748e-11,  6.31656748e-11,
        0.00000000e+00,  2.52662699e-10])

In [320]:
gradient_descent_PF([10,10,10,10,10,1,1,1,1,1],[6,7,3,9,3,4,1,1,0,4],'A')[1]

The learning rate is: 0.09090909090909091
The process converged in the interation: 132
The final value of f was: 1.841294249224644e-20


132

In [321]:
gradient_descent_PF([10,10,10,10,10,1,1,1,1,1],[6,7,3,9,3,4,1,1,0,4],'B')[1]

The learning rate is: 0.05
The process converged in the interation: 221
The final value of f was: 2.026133649330505e-19


221

In [349]:
gradient_descent_backtracking([100,100,100,100,100,50,50,50,10,1],[6,7,3,9,3,4,1,1,0,4],0.1,1)[0]

The process converged in the interation: 1035
The final value of f was: 1.3435155497446874e-19


array([-1.14202631e-12, -1.33236403e-12, -5.71013156e-13, -1.71303947e-12,
       -5.71013156e-13,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  3.65629528e-10])

In [350]:
gradient_descent_PF([100,100,100,100,100,50,50,50,10,1],[6,7,3,9,3,4,1,1,0,4],'A')[1]

The learning rate is: 0.009900990099009901
The process converged in the interation: 1432
The final value of f was: 2.4433074554056004e-21


1432

In [351]:
gradient_descent_PF([100,100,100,100,100,50,50,50,10,1],[6,7,3,9,3,4,1,1,0,4],'B')[1]

The learning rate is: 0.005
The process converged in the interation: 2269
The final value of f was: 2.492487944014172e-19


2269